name: Pytest BookingBike
on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev
  workflow_dispatch:

jobs:
  my_job:
    name: Contenedor Con Ubuntu
    runs-on:  ubuntu-latest
    steps:
      - uses:  actions/checkout@v4
      
      - name:  Instalando Python 3.8
        uses:  actions/setup-python@v4.3.1
        with:
          python-verion: 3.8
        
      - name:  Instalando dependencias
        run:  |
          python3 -m pip install --upgrade pip
          pip3 install -r requirements.txt
      - name: Test with pytest
        run: coverage run -m pytest -vv test/test_VIEW_main.py test/test_DB_conexionApiMongo.py test/test_DB_MongoAtlasConexion.py test/test_DB_generadorJson.py test/test_DB_convertirJsonALista.py test/test_DB_mainDB.py test/test_TYPER_listar_documentos.py test/test_TYPER_insertar_documento.py test/test_TYPER_actualizar_documento.py  test/test_TYPER_borrar_documento.py  test/test_CRUD_main.py
